# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: nvs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
      fail-fast: false  # Don't cancel other jobs when one job fails

    steps:
    - uses: actions/checkout@v3

    - name: Install zsh
      run: sudo apt install zsh
      if: ${{ runner.os == 'Linux' }}

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: nuget/setup-nuget@v2
      with:
    
        nuget-version: '5.x'
    - run: nuget restore ./setup/nvs.sln
    - run: vcbuild ./setup/build.yml
      if: ${{ runner.os != 'Linux' }}
    - name: Install packages
      run: npm install --no-optional

    - name: Run tests
      run: npm run test -- --tap

    - name: Check style
      run: npm run lint
      if: ${{ always() }}

    - name: Check types
      run: npm run ts-check
      if: ${{ always() }}
